[package]
name = "compile_with_bazel"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "fake_lib.rs"

[raze]
workspace_path = "//3rdparty/cargo"
genmode = "Remote"

#[raze.crates.proc-macro2.'1.0.8']
#additional_flags = [
#    "--cfg=use_proc_macro",
#]
#
#
#[raze.crates.proc-macro2.'0.4.30']
#additional_flags = [
#    "--cfg=use_proc_macro",
#]

[dependencies]
rand = "0.7.0"
