steps:
  - command: "bazel test //..."
    label: ":bazel: Build + Test"
  - command: "./tools/build/ci_lint_check.sh"
    label: ":lint-roller: Lint Check"
  - wait
  - command: "aws sts get-caller-identity"
#    branches: "master"